# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'easyocr',
        'torch',
        'torchaudio',
        'torchvision',
        'triton',
        'transformers',
        'diffusers',
        'accelerate',
        'imageio_ffmpeg',
        'huggingface_hub',
        'hf_xet',
        'tokenizers',
        'timm',
        'scipy',
        'skimage',
        'llvmlite',
        'numba',
        'pandas',
        'matplotlib',
        'IPython',
        'jedi',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Cleaner_Pro',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Cleaner_Pro',
)
